export const horoscopeData = {
  focus: [
    "Positive transformation", "New beginnings", "Mental clarity", "Emotional balance",
    "Creative inspiration", "True connections", "Financial prosperity", "Inner strength",
    "Renewed energy", "Determination", "Spiritual wisdom", "Self-confidence",
    "Unexpected opportunities", "Relationship harmony", "Focus and discipline",
    "Overcoming challenges", "Heightened intuition", "Genuine joy",
    "Recognition for efforts", "New partnerships"
  ],
  problems: [
    "Anxiety", "Confused communication", "Insecurity", "Procrastination",
    "Impulsiveness", "Lack of focus", "Family conflicts", "Hidden fears",
    "Disorganization", "Mental stress", "Unclear decision-making", "Social isolation",
    "Excessive self-criticism", "Lost opportunities due to hesitation", "Persistent doubts",
    "Jealousy and possessiveness", "Lack of patience", "Excessive distractions",
    "Resistance to change", "Physical fatigue"
  ],
  interpretations: {
    daily: [
        "Today, your focus and discipline will be tested, but remember the importance of acknowledging your efforts. As challenges arise, keep your mind clear; this will help reduce confusion and open the way for wise choices. Take a moment to send a kind message to someone — it may strengthen bonds and lift your spirit. Avoid harsh self-criticism and embrace the steps you’ve already taken toward growth.",
        "Today, your heart is drawn toward clarity and truth. You may feel the urge to confront something you’ve been avoiding, but do so with compassion for yourself and others. Breathe deeply before responding to tension, and you’ll find your words carry healing energy. Allow gratitude to guide your decisions, and peace will unfold in unexpected places.",
        "On this day, new opportunities may quietly present themselves. Keep your eyes open for small signs — they often lead to big shifts. Engage in conversations with genuine curiosity; you might uncover insight that reshapes your path. Release the need to control every outcome, and let trust in the process be your anchor.",
        "Today, your energy may feel scattered, yet this is an invitation to focus on what truly matters. Eliminate one distraction that has been weighing you down. Spend a few moments in silence, listening to your own breath. That inner calm will give you the clarity to take the next step toward your goals.",
        "On this day, you are being called to lead — even in small ways. Someone may look to you for advice or comfort, so offer it with sincerity. Remember that leadership is not about control, but about inspiring trust. Show others, through your actions, the kind of peace and balance you wish to see.",
        "Today, reflection will bring clarity. Take time to look back on how far you’ve come — acknowledge the victories and the lessons alike. This perspective will help you approach current challenges with more patience and strength. Your resilience is your quiet superpower.",
        "Today, you may feel the weight of uncertainty, but within it lies your opportunity for transformation. Resist the urge to rush for answers; instead, allow yourself to live in the question. A moment of quiet contemplation could reveal the insight you’ve been seeking.",
        "On this day, your interactions may carry more emotional depth than usual. Be present in conversations, listen fully, and respond with empathy. This openness can heal misunderstandings and strengthen relationships that matter most to you.",
        "Today, the universe asks you to slow down. Moving with intention will help you notice details you’ve been overlooking. Take time to enjoy something simple — a warm drink, the sound of music, or a walk in fresh air. Small joys can shift your whole energy.",
        "Today, you might face a decision that requires courage. Rather than seeking everyone’s opinion, trust your inner compass. You know more than you think, and your intuition is sharper than you realize. Act with quiet confidence.",
        "On this day, a spark of inspiration may arrive unexpectedly. Capture it before it fades — write it down, sketch it, or speak it aloud. This creative insight could be the seed of something life-changing.",
        "Today, let go of the need to prove yourself. You are already enough. Focus on doing things that bring you genuine satisfaction instead of chasing validation from others.",
        "On this day, a conversation could change the direction of your thoughts. Approach interactions with curiosity, and be open to hearing perspectives that differ from your own.",
        "Today, your heart may crave simplicity. Release one responsibility or habit that no longer feels aligned with your values. Create space for what truly matters.",
        "Today, a wave of nostalgia may arise, bringing memories to the surface. Let them guide you toward gratitude, even for the challenges that shaped you.",
        "On this day, your path may feel unclear, but clarity will come through patience. Avoid forcing solutions — let time reveal the right choice.",
        "Today, prioritize connection over perfection. Spend quality moments with people you care about, even if everything else feels chaotic.",
        "Today, inspiration may be found in nature. Step outside, feel the air, and notice how the world moves effortlessly around you. Let it remind you to release control.",
        "On this day, you may be tested in patience. Trust that the delay is part of a larger alignment that is preparing you for the right moment.",
        "Today, honor your emotions without letting them dictate your every move. Acknowledge what you feel, then choose actions that align with your deeper values.",
        "Today, a hidden blessing may emerge from something you once considered a setback. Keep your mind open to unexpected outcomes.",
        "On this day, practice kindness toward yourself. Speak to yourself as you would to a dear friend who needs encouragement.",
        "Today, you may feel drawn to start something new. Take one small step toward it, no matter how insignificant it seems.",
        "Today, focus on listening more than speaking. In the quiet, you may hear exactly what you need.",
        "Today, release the need to be everywhere at once. Center yourself and commit fully to one thing at a time.",
        "On this day, your inner strength will shine in subtle ways. Notice how you carry yourself — with grace, resilience, and quiet power.",
        "Today, be open to receiving help. Accepting support is not weakness; it’s a reminder that you are connected to others.",
        "Today, celebrate progress instead of perfection. Each step forward is a victory.",
        "On this day, trust that what is meant for you will not pass you by. Let this truth ease your worries.",
        "Today, choose peace over proving a point. Some battles are not worth your energy."
    ],
    weekly: [
        "This week, your patience will be tested, but so will your ability to trust divine timing. Steady, consistent effort will bring greater rewards than rushing toward quick fixes. Let time work in your favor.",
        "This week, focus on the connections that truly matter. Reach out to someone you’ve missed, and nurture the bonds that bring you joy.",
        "This week, challenges may appear bigger than they are. Remember that you’ve faced more difficult moments and emerged stronger.",
        "This week, explore something new — a hobby, a place, or a way of thinking. Fresh experiences can bring surprising solutions.",
        "This week, clarity will come through reflection. Spend time journaling to uncover insights you didn’t realize you had.",
        "This week, your creativity may spark in unexpected moments. Keep a notebook or voice recorder nearby to capture ideas before they fade.",
        "This week, a conversation could shift your perspective entirely. Be open to hearing advice, even if it challenges your current views.",
        "This week, prioritize rest as much as productivity. The quality of your actions will improve when you’re balanced.",
        "This week, avoid overcommitting yourself. Saying “no” to the wrong things is a way of saying “yes” to what truly matters.",
        "This week, an old lesson may resurface to guide you. Pay attention — it’s coming back for a reason.",
        "This week, focus on gratitude daily. Recognizing even small blessings will elevate your mood and mindset.",
        "This week, be intentional about your environment. The spaces you inhabit influence your energy more than you think.",
        "This week, a challenge may turn out to be a disguised opportunity. Approach it with curiosity rather than fear.",
        "This week, lean into collaboration. Working with others can reveal solutions you wouldn’t have discovered alone.",
        "This week, balance your plans with flexibility. Unexpected turns could lead to even better outcomes.",
        "This week, practice patience with others. Everyone is navigating their own unseen struggles.",
        "This week, align your actions with your deeper values. Let integrity guide your decisions.",
        "This week, inspiration may come from observing others. Watch, learn, and apply what resonates.",
        "This week, focus on building small habits that support your long-term goals. Consistency is more powerful than intensity.",
        "This week, release grudges you’ve been carrying. Forgiveness frees your energy for better things.",
        "This week, be mindful of your words. What you speak has the power to heal or harm.",
        "This week, seek out beauty in ordinary places. It will lift your spirit and keep you grounded.",
        "This week, a breakthrough could come when you least expect it. Stay alert and ready to act.",
        "This week, simplify your routines. Less clutter allows for more focus and peace.",
        "This week, express your appreciation to those who have supported you. Gratitude deepens relationships.",
        "This week, spend time outdoors to reset your energy. Nature has a way of restoring clarity.",
        "This week, take a bold step toward something you’ve been postponing. The right moment is now.",
        "This week, invest in learning something new. Expanding your mind opens new doors.",
        "This week, honor your boundaries. Protect your time and energy from unnecessary drains.",
        "This week, celebrate small milestones. Every step forward matters."
    ],
    monthly: [
        "This month, prepare for meaningful transformation. Stagnant situations will shift, creating room for new beginnings.",
        "In the next 30 days, focus on nurturing your inner world alongside your outer goals. Self-care will fuel your success.",
        "This month, relationships will be key to your growth. Notice who inspires you and who drains you — and adjust accordingly.",
        "Over the next 30 days, release what no longer serves you. Letting go makes space for something better.",
        "This month, be bold in speaking your truth. Honesty will align you with the right people and opportunities.",
        "This month, unexpected blessings may arrive disguised as challenges. Stay open to the lessons they bring.",
        "In the next 30 days, commit to one personal goal and give it your full attention. Focus amplifies results.",
        "This month, take time to reflect on your journey so far. The lessons you’ve learned are tools for your next chapter.",
        "Over the next month, be mindful of the energy you absorb. Protect your peace.",
        "This month, new opportunities may align with your deepest passions. Say yes to what excites your soul.",
        "This month, be intentional about the company you keep. The right people will lift you higher.",
        "In the next 30 days, practice patience. What’s unfolding for you is worth the wait.",
        "This month, focus on building foundations. Solid groundwork ensures lasting growth.",
        "Over the next month, listen to your intuition more than outside noise. Your inner voice knows the way.",
        "This month, an important decision will require courage. Trust that you have the strength to make it.",
        "This month, create space in your life for joy. Schedule it as you would any important commitment.",
        "Over the next 30 days, your consistency will be rewarded. Keep going, even when progress feels slow.",
        "This month, release old fears. They no longer have a place in the person you’re becoming.",
        "This month, a reconnection with someone from your past may bring closure or new beginnings.",
        "Over the next month, focus on gratitude daily. It will shift your perspective on every challenge.",
        "This month, you may feel called to explore something completely new. Follow that curiosity.",
        "This month, be kind to yourself through the ups and downs. You’re still moving forward.",
        "In the next 30 days, expect moments of clarity that change your path for the better.",
        "This month, take small but steady steps toward your dreams. Momentum builds over time.",
        "Over the next month, embrace change rather than resist it. It’s guiding you somewhere important.",
        "This month, invest in your personal growth. Books, courses, and new experiences will expand your horizons.",
        "In the next 30 days, trust the timing of your life. You are exactly where you need to be.",
        "This month, focus on balance. Give as much energy to your inner world as to your outer achievements.",
        "Over the next month, let go of unrealistic expectations. Peace comes from accepting what is.",
        "This month, celebrate how far you’ve come. Every step, even the small ones, has led you here."
    ]
  }
};