// Mock functions for development
// In a real app, these would be actual API endpoints

export const sendNotification = async (data) => {
  console.log('Mock sendNotification:', data);
  return { success: true };
};

export const initializeFirebase = async (data) => {
  console.log('Mock initializeFirebase:', data);
  return { success: true };
};

export const sendPushNotification = async (data) => {
  console.log('Mock sendPushNotification:', data);
  return { 
    data: { 
      success: true, 
      fcm_response: { success: 1, failure: 0 } 
    } 
  };
};

export const scheduleDailyNotifications = async (data) => {
  console.log('Mock scheduleDailyNotifications:', data);
  return { success: true };
};

export const createCheckoutSession = async (data) => {
  console.log('Mock createCheckoutSession:', data);
  // Mock Stripe checkout URL
  return { 
    data: { 
      url: 'https://checkout.stripe.com/pay/mock-session-id' 
    } 
  };
};

export const stripeWebhook = async (data) => {
  console.log('Mock stripeWebhook:', data);
  return { success: true };
};

export const logCoinTransaction = async (data) => {
  console.log('Mock logCoinTransaction:', data);
  
  // Store transaction in localStorage for mock persistence
  const transactions = JSON.parse(localStorage.getItem('CoinTransaction_data') || '[]');
  const newTransaction = {
    id: Date.now().toString(),
    created_date: new Date().toISOString(),
    ...data
  };
  transactions.push(newTransaction);
  localStorage.setItem('CoinTransaction_data', JSON.stringify(transactions));
  
  return { success: true };
};

export const cartpandaWebhook = async (data) => {
  console.log('Mock cartpandaWebhook:', data);
  return { success: true };
};

export const simulateAdvisorResponse = async (data) => {
  console.log('Mock simulateAdvisorResponse:', data);
  return { 
    response: "This is a mock advisor response. In a real app, this would be generated by AI." 
  };
};

export const hotmartWebhook = async (data) => {
  console.log('Mock hotmartWebhook:', data);
  return { success: true };
};